# Generated by Django 5.1.6 on 2025-02-13 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BiblioApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Abonnement',
        ),
        migrations.RemoveField(
            model_name='livre',
            name='auteur',
        ),
        migrations.RemoveField(
            model_name='universite',
            name='id_campus',
        ),
        migrations.RemoveField(
            model_name='classe',
            name='id_departement',
        ),
        migrations.RemoveField(
            model_name='compartiment',
            name='etagere',
        ),
        migrations.RemoveField(
            model_name='departement',
            name='id_faculte',
        ),
        migrations.RemoveField(
            model_name='etagere',
            name='id_emplacement',
        ),
        migrations.RemoveField(
            model_name='livre',
            name='id_emplacement',
        ),
        migrations.RemoveField(
            model_name='etranger',
            name='id_emprunt',
        ),
        migrations.RemoveField(
            model_name='personne',
            name='id_emprunt',
        ),
        migrations.RemoveField(
            model_name='etudiant',
            name='id_emprunt',
        ),
        migrations.RemoveField(
            model_name='faculte',
            name='id_universite',
        ),
        migrations.DeleteModel(
            name='Auteur',
        ),
        migrations.DeleteModel(
            name='Campus',
        ),
        migrations.DeleteModel(
            name='Classe',
        ),
        migrations.DeleteModel(
            name='Compartiment',
        ),
        migrations.DeleteModel(
            name='Departement',
        ),
        migrations.DeleteModel(
            name='Etagere',
        ),
        migrations.DeleteModel(
            name='Emplacement',
        ),
        migrations.DeleteModel(
            name='Livre',
        ),
        migrations.DeleteModel(
            name='Etranger',
        ),
        migrations.DeleteModel(
            name='Personne',
        ),
        migrations.DeleteModel(
            name='Emprunt',
        ),
        migrations.DeleteModel(
            name='Etudiant',
        ),
        migrations.DeleteModel(
            name='Faculte',
        ),
        migrations.DeleteModel(
            name='Universite',
        ),
    ]
