# Generated by Django 5.1.6 on 2025-02-13 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abonnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_abonnement', models.CharField(max_length=100)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Auteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campus', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departement', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Emplacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Emprunt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_emprunt', models.DateTimeField(auto_now_add=True)),
                ('date_retour', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Faculte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculte', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau', models.CharField(max_length=100)),
                ('id_departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BiblioAPI.departement')),
            ],
        ),
        migrations.CreateModel(
            name='Etagere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('etat_etagere', models.CharField(max_length=50)),
                ('mobilite', models.BooleanField(default=False)),
                ('charge_maximal', models.DecimalField(decimal_places=3, max_digits=100)),
                ('id_emplacement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BiblioAPI.emplacement')),
            ],
        ),
        migrations.CreateModel(
            name='Compartiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('nombreLivre', models.IntegerField()),
                ('etagere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BiblioAPI.etagere')),
            ],
        ),
        migrations.CreateModel(
            name='Etranger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('genre', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin'), ('A', 'Autre')], max_length=1)),
                ('photo_passport', models.ImageField(blank=True, null=True, upload_to='photos_passport/')),
                ('datenaissance', models.DateField()),
                ('CNI', models.CharField(max_length=20, unique=True)),
                ('id_emprunt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BiblioAPI.emprunt')),
            ],
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('genre', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin'), ('A', 'Autre')], max_length=1)),
                ('photo_passport', models.ImageField(blank=True, null=True, upload_to='photos_passport/')),
                ('datenaissance', models.DateField()),
                ('id_emprunt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BiblioAPI.emprunt')),
            ],
        ),
        migrations.AddField(
            model_name='departement',
            name='id_faculte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BiblioAPI.faculte'),
        ),
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('langueLivre', models.CharField(choices=[('FR', 'Français'), ('EN', 'Anglais'), ('ES', 'Espagnol'), ('DE', 'Allemand')], max_length=2)),
                ('annee_publication', models.PositiveIntegerField()),
                ('nombrepages', models.PositiveIntegerField()),
                ('imageLivre', models.ImageField(blank=True, null=True, upload_to='images_livres/')),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BiblioAPI.auteur')),
                ('id_emplacement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BiblioAPI.emplacement')),
            ],
        ),
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('genre', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin'), ('A', 'Autre')], max_length=1)),
                ('profil', models.ImageField(blank=True, null=True, upload_to='photos_passport/')),
                ('tel', models.CharField(blank=True, max_length=15)),
                ('matricule', models.CharField(max_length=50, unique=True)),
                ('datenaissance', models.DateField()),
                ('CNI', models.CharField(max_length=20, unique=True)),
                ('id_emprunt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BiblioAPI.emprunt')),
            ],
        ),
        migrations.CreateModel(
            name='Universite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('pays', models.CharField(max_length=100)),
                ('ville', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('site_web', models.URLField()),
                ('id_campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BiblioAPI.campus')),
            ],
        ),
        migrations.AddField(
            model_name='faculte',
            name='id_universite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BiblioAPI.universite'),
        ),
    ]
